### ISSUE TITLE
Message-ID permalinks don’t work for messages with folded message ID headers

### ISSUE THREAD

**Issue by ap** [perlorg/cnntp#7]
Clicking the “Message ID” link on any of the following pages leads to a 404 instead of right back to the same page (as it should):

https://www.nntp.perl.org/group/perl.perl5.porters/2016/11/msg240764.html
https://www.nntp.perl.org/group/perl.perl5.porters/2017/07/msg245527.html
https://www.nntp.perl.org/group/perl.perl5.porters/2019/07/msg255706.html

The same is true for lots of other messages. Their commonality is that the `Message-ID:` header name is on one line by itself and then the actual `<blahblahblah@where.ever>` message ID follows on the next line with continuation whitespace.

I am not sure whether the culprit here is cnntp or colobus, since I haven’t succeeded in getting them running and from trying to read the code it’s not obvious to me where this might be happening. I am strongly suspecting that this involves a pattern match without a `/s` somewhere where it’s needed, but I haven’t been able to spot something like that. Colobus largely just uses an unanchored `<(.+?)>` as the pattern to parse the header, which is fine.

**Comment by rspier** [comment]
It's an indexing problem.

https://www.nntp.perl.org/group/perl.perl5.porters/2016/11/msg240764.html

should have

    299104897.682.1478179708456.JavaMail.jenkins@jenkins-001.ams6.corp.booking.com

but has

    <perl.perl5.porters-240764@nntp.perl.org>

instead.

That comes from

      # make sure we have a message-id
      $xover{'Message-ID'} ||= "<$group-$artno\@$config{servername}>";

in `colubus-archive`.

I think the actual problem is:

        if ($line =~ m/^$header: (.+?)\r?\n/is) {

which requires a space after the `:`.  

Looking in the toolbox, at some point in 2002 I (probably) made a version with the smarter

        if ($line =~ m/^$header: *(.*)\r?\n/is) {

**Comment by ap** [comment]
> Looking in the toolbox, at some point in 2002 I (probably) made a version with the smarter

Funnily enough that’s (also?) the currently most recent commit, abh/colobus@288ade5d069d59316a508fe8aba48807cf3cb083 from 2022.

So all that’s needed is to actually deploy current `master`?

**Comment by ap** [comment]
@rspier Any movement on this front?

**Comment by rspier** [comment]
There wasn't.  But I did it tonight.  There were some complications, which is expected for a nearly 25 year old legacy system.  (Pretty cool it still works!)

The code change was simple, but then I had to run a backfill on the 10.000 posts which had triggered the issue.

I believe it's fixed now.

**Comment by ap** [comment]
Looks good. Thank you!
