### ISSUE TITLE
Message-ID permalinks often don’t work on the first try

### ISSUE THREAD

**Issue by ap** [perlorg/cnntp#8]
I think this didn’t used to be the case, but I get it a lot nowadays: I click a link to a `;msgid=` URL, even one I know is there, and I get a 404. If I wait half a minute and refresh the same tab, it then works.

The same link will fail again in the same way after some time, at least sometimes.

It seems like there is a cache with buggy cache miss update logic involved somewhere. But I haven’t spent any time looking at code, I’m just reporting the behavior I see, so I don’t know if my guess is at all right.

**Comment by rspier** [comment]
Can you provide some example links and when the failure happened?

**Comment by abh** [comment]
[ eh, I posted a draft of my message before I'd figured it out, maybe -- updating ].

```
curl -vo/dev/null 'https://www.nntp.perl.org/group/perl.dbi.dev/;msgid=27381.1732454989%40rock.martins.cc'
```

gives 301 when it hits a pod built from the main branch, and 404 when it goes to a pod with OpenTelemetry (which requires Net::Async::HTTP::Server), built from the `tracing` branch.

I think it's a bug in Net::Async::HTTP::Server.   I emailed a patch to @leonerd in February; I'll try building cnntp with that.

**Comment by rspier** [comment]
We already rolled out the parking patch.  This is something else.

**Comment by abh** [comment]
parking? :-)  Doing a build now with e60c6aae.

**Comment by rspier** [comment]
I'm thinking of a different bug.

**Comment by abh** [comment]
`curl -vo/dev/null 'https://www.nntp.perl.org/group/perl.dbi.dev/;msgid=27381.1732454989@rock.martins.cc'` works, so it is something with the other Plack implementation not URI decoding the `;` parameter. (Why I used that instead of `?`... ugh).  Have to do something else for the rest of the evening.

**Comment by abh** [comment]
Looks like that fixed it...  @ap, does it seem better to you too?

**Comment by ap** [comment]
It does.

I don’t know how else to check so I went down the entire list at https://psc.perlhacks.com/ and clicked every list archive link, and all 170 of them worked on the first try, when at other times there would have been *some* exception.

I can’t know whether that’s because the bug is gone or because all 170 of them just happened to be hit recently, so I can’t say for sure. But the odds of the latter seem low so I’ll go with that.

Can always reopen or re-file the issue if it isn’t fixed after all.

**Comment by ap** [comment]
Thanks for the rapid turnaround!

**Comment by abh** [comment]
nice, thanks for testing!

It wasn't a caching thing but rather a 60/40% random traffic split that decided if you got the error or not.

**Comment by abh** [comment]
Someone deleted the four patches I sent to rt.cpan.org, so I guess it won't be fixed. Time to rewrite it in Go?

**Comment by ap** [comment]
I’m not sure why he deleted it but jdporter@ is not a maintainer of the module, nor AFAICT has he ever been. I’m not one either, but I can undelete it, so I have (without having any special permissions – so I assume you could as well?).

The subject says it’s patch 4 out of 4, but I see no other patches in the queue (whether active or resolved), so I guess they also got deleted? If yes and you can’t undelete them yourself or don’t want to, lemme know the issue IDs and I’m happy to do it for you.

**Comment by abh** [comment]
thanks @ap; I didn't realize anyone can delete or undelete! I undeleted the other three. It looks like the other person were just trying to clean out spam to the system and included a few too many.

**Comment by ap** [comment]
> (Why I used that instead of `?`... ugh)

That makes sense to me in terms of URI design btw. A `;` is part of the path segment in a URI, not a parameter to the URL as a whole. Meaning that semantically, this isn’t a group URL with a weirdly written query parameter, it’s a message permalink where the message ID component of the URL specifies the message not by the numeric storage ID of the message but by indicating its Message-ID using a segment-specific parameter.

**Comment by rspier** [comment]
Before 2014 this was a valid alternative.  But the W3C recommendation changed.

**Comment by ap** [comment]
> But the W3C recommendation changed.

Ah. Do you have a pointer to that? Would love to update myself.

**Comment by rspier** [comment]
[The 1999 reccomendation](https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2) says

> We recommend that HTTP server implementors, and in particular, CGI implementors support the use of ";" in place of "&" to save authors the trouble of escaping "&" characters in this manner.

[The 2014 version](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data) says

> Let strings be the result of [strictly splitting the string](https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#strictly-split-a-string) payload on U+0026 AMPERSAND characters (&).


[via so](https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator)

**Comment by ap** [comment]
Oh, that. Right, I was aware of that – but there are no query parameters in this case, because there is no `?` in the URL, so the change in the recommendation concerning query parameter separators is irrelevant.

So after doing a quick bit of digging, it appears that the most recent URI spec is still [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) after all these years. On the [the path part of the URI](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3), that RFC has this to say:

> A path consists of a sequence of path segments separated by a slash ("/") character. […] Aside from dot-segments in hierarchical paths, a path segment is considered opaque by the generic syntax. URI producing applications often use the reserved characters allowed in a segment to delimit scheme-specific or dereference-handler-specific subcomponents. For example, the semicolon (";") and equals ("=") reserved characters are often used to delimit parameters and parameter values *applicable to that segment*.

(Emphasis mine.)

That is what’s going on here.
